version: "3.8"
services:
  frontend:
    image: brandmonks/wavdio-angular
    restart: always
    ports:
      - "8080:80"
    networks:
      - frontend
  backend:
    image: brandmonks/wavdio-express
    restart: always
    volumes:
      - backenddata1:/app/uploads
      - backenddata2:/app/upload
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=db
    networks:
      - backend
      - frontend
  db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      # - MONGO_REPLICA_HOST=db
    volumes:
      - dbdata:/data/db
    networks:
      - backend
volumes:
  dbdata:
  backenddata1:
  backenddata2:
networks:
  frontend:
  backend:
